"""Remove obsolete columns from past dispatch tables and dispatched_at from items

Revision ID: 22c267ffefcb
Revises: c74d6621b178
Create Date: 2025-08-29 18:02:20.573146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c267ffefcb'
down_revision: Union[str, None] = 'c74d6621b178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_dispatch_item', sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('past_dispatch_item', 'dispatched_at')
    op.drop_column('past_dispatch_item', 'barcode_id')
    op.drop_column('past_dispatch_item', 'qr_code')
    op.drop_column('past_dispatch_item', 'status')
    op.drop_column('past_dispatch_record', 'reference_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_dispatch_record', sa.Column('reference_number', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('past_dispatch_item', sa.Column('status', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('past_dispatch_item', sa.Column('qr_code', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    op.add_column('past_dispatch_item', sa.Column('barcode_id', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('past_dispatch_item', sa.Column('dispatched_at', sa.DATETIME(), autoincrement=False, nullable=False))
    op.drop_column('past_dispatch_item', 'rate')
    # ### end Alembic commands ###
