"""Initial master-based architecture

Revision ID: 3c7e5b80a833
Revises: 
Create Date: 2025-07-24 12:53:12.636265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '3c7e5b80a833'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_master_id'), 'user_master', ['id'], unique=False)
    op.create_index(op.f('ix_user_master_username'), 'user_master', ['username'], unique=True)
    op.create_table('client_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_master_company_name'), 'client_master', ['company_name'], unique=False)
    op.create_index(op.f('ix_client_master_id'), 'client_master', ['id'], unique=False)
    op.create_table('paper_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('gsm', sa.Integer(), nullable=False),
    sa.Column('bf', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('shade', sa.String(length=50), nullable=False),
    sa.Column('thickness', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_master_bf'), 'paper_master', ['bf'], unique=False)
    op.create_index(op.f('ix_paper_master_gsm'), 'paper_master', ['gsm'], unique=False)
    op.create_index(op.f('ix_paper_master_id'), 'paper_master', ['id'], unique=False)
    op.create_index(op.f('ix_paper_master_name'), 'paper_master', ['name'], unique=False)
    op.create_index(op.f('ix_paper_master_shade'), 'paper_master', ['shade'], unique=False)
    op.create_table('plan_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('cut_pattern', sa.Text(), nullable=False),
    sa.Column('expected_waste_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('actual_waste_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_master_id'), 'plan_master', ['id'], unique=False)
    op.create_index(op.f('ix_plan_master_status'), 'plan_master', ['status'], unique=False)
    op.create_table('order_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('client_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('paper_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('width_inches', sa.Integer(), nullable=False),
    sa.Column('quantity_rolls', sa.Integer(), nullable=False),
    sa.Column('quantity_fulfilled', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_master.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_master_client_id'), 'order_master', ['client_id'], unique=False)
    op.create_index(op.f('ix_order_master_id'), 'order_master', ['id'], unique=False)
    op.create_index(op.f('ix_order_master_paper_id'), 'order_master', ['paper_id'], unique=False)
    op.create_index(op.f('ix_order_master_status'), 'order_master', ['status'], unique=False)
    op.create_table('production_order_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('paper_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_order_master_id'), 'production_order_master', ['id'], unique=False)
    op.create_index(op.f('ix_production_order_master_paper_id'), 'production_order_master', ['paper_id'], unique=False)
    op.create_index(op.f('ix_production_order_master_status'), 'production_order_master', ['status'], unique=False)
    op.create_table('inventory_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('paper_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('width_inches', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('roll_type', sa.String(length=20), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('production_date', sa.DateTime(), nullable=False),
    sa.Column('allocated_to_order_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocated_to_order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_master_id'), 'inventory_master', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_master_paper_id'), 'inventory_master', ['paper_id'], unique=False)
    op.create_index(op.f('ix_inventory_master_qr_code'), 'inventory_master', ['qr_code'], unique=True)
    op.create_index(op.f('ix_inventory_master_roll_type'), 'inventory_master', ['roll_type'], unique=False)
    op.create_index(op.f('ix_inventory_master_status'), 'inventory_master', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_master_width_inches'), 'inventory_master', ['width_inches'], unique=False)
    op.create_table('pending_order_master',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('order_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('paper_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('width_inches', sa.Integer(), nullable=False),
    sa.Column('quantity_pending', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('production_order_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_master.id'], ),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_order_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_order_master_id'), 'pending_order_master', ['id'], unique=False)
    op.create_index(op.f('ix_pending_order_master_order_id'), 'pending_order_master', ['order_id'], unique=False)
    op.create_index(op.f('ix_pending_order_master_paper_id'), 'pending_order_master', ['paper_id'], unique=False)
    op.create_index(op.f('ix_pending_order_master_status'), 'pending_order_master', ['status'], unique=False)
    op.create_table('plan_order_link',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('plan_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('order_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_order_link_id'), 'plan_order_link', ['id'], unique=False)
    op.create_index(op.f('ix_plan_order_link_order_id'), 'plan_order_link', ['order_id'], unique=False)
    op.create_index(op.f('ix_plan_order_link_plan_id'), 'plan_order_link', ['plan_id'], unique=False)
    op.create_table('plan_inventory_link',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('plan_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('inventory_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('quantity_used', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_master.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_inventory_link_id'), 'plan_inventory_link', ['id'], unique=False)
    op.create_index(op.f('ix_plan_inventory_link_inventory_id'), 'plan_inventory_link', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_plan_inventory_link_plan_id'), 'plan_inventory_link', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plan_inventory_link_plan_id'), table_name='plan_inventory_link')
    op.drop_index(op.f('ix_plan_inventory_link_inventory_id'), table_name='plan_inventory_link')
    op.drop_index(op.f('ix_plan_inventory_link_id'), table_name='plan_inventory_link')
    op.drop_table('plan_inventory_link')
    op.drop_index(op.f('ix_plan_order_link_plan_id'), table_name='plan_order_link')
    op.drop_index(op.f('ix_plan_order_link_order_id'), table_name='plan_order_link')
    op.drop_index(op.f('ix_plan_order_link_id'), table_name='plan_order_link')
    op.drop_table('plan_order_link')
    op.drop_index(op.f('ix_pending_order_master_status'), table_name='pending_order_master')
    op.drop_index(op.f('ix_pending_order_master_paper_id'), table_name='pending_order_master')
    op.drop_index(op.f('ix_pending_order_master_order_id'), table_name='pending_order_master')
    op.drop_index(op.f('ix_pending_order_master_id'), table_name='pending_order_master')
    op.drop_table('pending_order_master')
    op.drop_index(op.f('ix_inventory_master_width_inches'), table_name='inventory_master')
    op.drop_index(op.f('ix_inventory_master_status'), table_name='inventory_master')
    op.drop_index(op.f('ix_inventory_master_roll_type'), table_name='inventory_master')
    op.drop_index(op.f('ix_inventory_master_qr_code'), table_name='inventory_master')
    op.drop_index(op.f('ix_inventory_master_paper_id'), table_name='inventory_master')
    op.drop_index(op.f('ix_inventory_master_id'), table_name='inventory_master')
    op.drop_table('inventory_master')
    op.drop_index(op.f('ix_production_order_master_status'), table_name='production_order_master')
    op.drop_index(op.f('ix_production_order_master_paper_id'), table_name='production_order_master')
    op.drop_index(op.f('ix_production_order_master_id'), table_name='production_order_master')
    op.drop_table('production_order_master')
    op.drop_index(op.f('ix_order_master_status'), table_name='order_master')
    op.drop_index(op.f('ix_order_master_paper_id'), table_name='order_master')
    op.drop_index(op.f('ix_order_master_id'), table_name='order_master')
    op.drop_index(op.f('ix_order_master_client_id'), table_name='order_master')
    op.drop_table('order_master')
    op.drop_index(op.f('ix_plan_master_status'), table_name='plan_master')
    op.drop_index(op.f('ix_plan_master_id'), table_name='plan_master')
    op.drop_table('plan_master')
    op.drop_index(op.f('ix_paper_master_shade'), table_name='paper_master')
    op.drop_index(op.f('ix_paper_master_name'), table_name='paper_master')
    op.drop_index(op.f('ix_paper_master_id'), table_name='paper_master')
    op.drop_index(op.f('ix_paper_master_gsm'), table_name='paper_master')
    op.drop_index(op.f('ix_paper_master_bf'), table_name='paper_master')
    op.drop_table('paper_master')
    op.drop_index(op.f('ix_client_master_id'), table_name='client_master')
    op.drop_index(op.f('ix_client_master_company_name'), table_name='client_master')
    op.drop_table('client_master')
    op.drop_index(op.f('ix_user_master_username'), table_name='user_master')
    op.drop_index(op.f('ix_user_master_id'), table_name='user_master')
    op.drop_table('user_master')
    # ### end Alembic commands ###
