"""Add barcode_id fields to CutRollProduction and InventoryMaster

Revision ID: 554d24e7a69a
Revises: bec2d6fcbf50
Create Date: 2025-08-02 13:18:43.908166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '554d24e7a69a'
down_revision: Union[str, None] = 'bec2d6fcbf50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cut_roll_production', sa.Column('barcode_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_cut_roll_production_barcode_id'), 'cut_roll_production', ['barcode_id'], unique=True)
    op.add_column('inventory_master', sa.Column('barcode_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_inventory_master_barcode_id'), 'inventory_master', ['barcode_id'], unique=True)
    op.add_column('dispatch_item', sa.Column('barcode_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispatch_item', 'barcode_id')
    op.drop_index(op.f('ix_inventory_master_barcode_id'), table_name='inventory_master')
    op.drop_column('inventory_master', 'barcode_id')
    op.drop_index(op.f('ix_cut_roll_production_barcode_id'), table_name='cut_roll_production')
    op.drop_column('cut_roll_production', 'barcode_id')
    # ### end Alembic commands ###
