"""add_pending_order_item_table

Revision ID: 6993ae0490f3
Revises: c46cd4399cc0
Create Date: 2025-07-27 13:52:05.452183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER


# revision identifiers, used by Alembic.
revision: str = '6993ae0490f3'
down_revision: Union[str, None] = 'c46cd4399cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
      # ### commands auto generated by Alembic - please adjust! ###        
      op.create_table('pending_order_item',
      sa.Column('id', UNIQUEIDENTIFIER(), nullable=False),
      sa.Column('original_order_id', UNIQUEIDENTIFIER(),
  nullable=False),
      sa.Column('width_inches', sa.Integer(), nullable=False),
      sa.Column('gsm', sa.Integer(), nullable=False),
      sa.Column('bf', sa.Numeric(precision=4, scale=2),
  nullable=False),
      sa.Column('shade', sa.String(length=50), nullable=False),
      sa.Column('quantity_pending', sa.Integer(), nullable=False),
      sa.Column('reason', sa.String(length=100), nullable=False),
      sa.Column('status', sa.String(length=50), nullable=False),
      sa.Column('production_order_id', UNIQUEIDENTIFIER(),
  nullable=True),
      sa.Column('created_by_id', UNIQUEIDENTIFIER(),
  nullable=True),
      sa.Column('created_at', sa.DateTime(), nullable=False),
      sa.Column('resolved_at', sa.DateTime(), nullable=True),
      sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'],       
  ),
      sa.ForeignKeyConstraint(['original_order_id'],
  ['order_master.id'], ),
      sa.ForeignKeyConstraint(['production_order_id'],
  ['production_order_master.id'], ),
      sa.PrimaryKeyConstraint('id')
      )
      op.create_index(op.f('ix_pending_order_item_id'),
  'pending_order_item', ['id'], unique=False)
      op.create_index(op.f('ix_pending_order_item_original_order_id'),     
   'pending_order_item', ['original_order_id'], unique=False)
      op.create_index(op.f('ix_pending_order_item_status'),
  'pending_order_item', ['status'], unique=False)
      # ### end Alembic commands ###


def downgrade() -> None:
      # ### commands auto generated by Alembic - please adjust! ###        
      op.drop_index(op.f('ix_pending_order_item_status'),
  table_name='pending_order_item')
      op.drop_index(op.f('ix_pending_order_item_original_order_id'),       
  table_name='pending_order_item')
      op.drop_index(op.f('ix_pending_order_item_id'),
  table_name='pending_order_item')
      op.drop_table('pending_order_item')
      # ### end Alembic commands ###
