"""Add quantity_fulfilled column to pending_order_item table

Revision ID: 8bf8b4d8007d
Revises: 554d24e7a69a
Create Date: 2025-08-04 13:15:29.745919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bf8b4d8007d'
down_revision: Union[str, None] = '554d24e7a69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cut_roll_production_barcode_id', table_name='cut_roll_production')
    op.create_index(op.f('ix_cut_roll_production_barcode_id'), 'cut_roll_production', ['barcode_id'], unique=False)
    op.add_column('pending_order_item', sa.Column('quantity_fulfilled', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_order_item', 'quantity_fulfilled')
    op.drop_index(op.f('ix_cut_roll_production_barcode_id'), table_name='cut_roll_production')
    op.create_index('ix_cut_roll_production_barcode_id', 'cut_roll_production', ['barcode_id'], unique=True)
    # ### end Alembic commands ###
