"""enhance_order_models_with_payment_weight_rate

Revision ID: a8c0f12c021f
Revises: 047cd19e0c1c
Create Date: 2025-07-26 18:26:55.075778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'a8c0f12c021f'
down_revision: Union[str, None] = '047cd19e0c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # First, add columns as nullable with defaults to avoid SQL Server constraint errors
    op.add_column('order_item', sa.Column('paper_id', mssql.UNIQUEIDENTIFIER(), nullable=True, server_default=sa.text('NEWID()')))
    op.add_column('order_item', sa.Column('quantity_kg', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
    op.add_column('order_item', sa.Column('rate', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
    op.add_column('order_item', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True, server_default='0.00'))
    
    # Get the first paper_id to use as default for existing order items
    op.execute("""
        UPDATE oi
        SET paper_id = (
            SELECT TOP 1 id FROM paper_master
        ),
        quantity_kg = width_inches * quantity_rolls * 13,
        rate = 100.00,
        amount = width_inches * quantity_rolls * 13 * 100.00
        FROM order_item oi
        WHERE paper_id IS NULL
    """)
    
    # Now make them NOT NULL
    op.alter_column('order_item', 'paper_id', existing_type=mssql.UNIQUEIDENTIFIER(), nullable=False, server_default=None)
    op.alter_column('order_item', 'quantity_kg', existing_type=sa.Numeric(precision=10, scale=2), nullable=False, server_default=None)
    op.alter_column('order_item', 'rate', existing_type=sa.Numeric(precision=10, scale=2), nullable=False, server_default=None)
    op.alter_column('order_item', 'amount', existing_type=sa.Numeric(precision=12, scale=2), nullable=False, server_default=None)
    
    op.create_index(op.f('ix_order_item_paper_id'), 'order_item', ['paper_id'], unique=False)
    op.create_foreign_key(None, 'order_item', 'paper_master', ['paper_id'], ['id'])
    
    # Add payment_type with default
    op.add_column('order_master', sa.Column('payment_type', sa.String(length=20), nullable=False, server_default='bill'))
    
    # Handle the paper_id removal from order_master
    op.drop_index('ix_order_master_paper_id', table_name='order_master')
    op.drop_constraint('FK__order_mas__paper__693CA210', 'order_master', type_='foreignkey')
    op.drop_column('order_master', 'paper_id')
    
    # Note: pending_order_master and plan_order_link already have order_item_id from previous migration
    # Just need to update foreign key references if needed


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_order_link', type_='foreignkey')
    op.drop_index(op.f('ix_plan_order_link_order_item_id'), table_name='plan_order_link')
    op.drop_column('plan_order_link', 'order_item_id')
    op.drop_constraint(None, 'pending_order_master', type_='foreignkey')
    op.drop_index(op.f('ix_pending_order_master_order_item_id'), table_name='pending_order_master')
    op.drop_column('pending_order_master', 'order_item_id')
    op.add_column('order_master', sa.Column('paper_id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False))
    op.create_foreign_key('FK__order_mas__paper__693CA210', 'order_master', 'paper_master', ['paper_id'], ['id'])
    op.create_index('ix_order_master_paper_id', 'order_master', ['paper_id'], unique=False)
    op.drop_column('order_master', 'payment_type')
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.drop_index(op.f('ix_order_item_paper_id'), table_name='order_item')
    op.drop_column('order_item', 'amount')
    op.drop_column('order_item', 'rate')
    op.drop_column('order_item', 'quantity_kg')
    op.drop_column('order_item', 'paper_id')
    # ### end Alembic commands ###
