"""pending order fixes

Revision ID: b7e4e57afaa4
Revises: 8bf8b4d8007d
Create Date: 2025-08-05 17:29:39.690943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7e4e57afaa4'
down_revision: Union[str, None] = '8bf8b4d8007d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with proper default values for SQL Server
    op.add_column('pending_order_item', sa.Column('included_in_plan_generation', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('pending_order_item', sa.Column('generated_cut_rolls_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pending_order_item', sa.Column('plan_generation_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_pending_order_item_included_in_plan_generation'), 'pending_order_item', ['included_in_plan_generation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_order_item_included_in_plan_generation'), table_name='pending_order_item')
    op.drop_column('pending_order_item', 'plan_generation_date')
    op.drop_column('pending_order_item', 'generated_cut_rolls_count')
    op.drop_column('pending_order_item', 'included_in_plan_generation')
    # ### end Alembic commands ###
