"""add_cut_roll_production_table

Revision ID: c46cd4399cc0
Revises: a8c0f12c021f
Create Date: 2025-07-27 08:50:46.457821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'c46cd4399cc0'
down_revision: Union[str, None] = 'a8c0f12c021f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cut_roll_production',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('width_inches', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('length_meters', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('actual_weight_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('paper_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('gsm', sa.Integer(), nullable=False),
    sa.Column('bf', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('shade', sa.String(length=100), nullable=False),
    sa.Column('plan_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('order_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('client_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('individual_roll_number', sa.Integer(), nullable=True),
    sa.Column('trim_left', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=False),
    sa.Column('production_started_at', sa.DateTime(), nullable=True),
    sa.Column('production_completed_at', sa.DateTime(), nullable=True),
    sa.Column('weight_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', mssql.UNIQUEIDENTIFIER(), nullable=False),
    sa.Column('weight_recorded_by_id', mssql.UNIQUEIDENTIFIER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client_master.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user_master.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_master.id'], ),
    sa.ForeignKeyConstraint(['paper_id'], ['paper_master.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_master.id'], ),
    sa.ForeignKeyConstraint(['weight_recorded_by_id'], ['user_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cut_roll_production_client_id'), 'cut_roll_production', ['client_id'], unique=False)
    op.create_index(op.f('ix_cut_roll_production_id'), 'cut_roll_production', ['id'], unique=False)
    op.create_index(op.f('ix_cut_roll_production_order_id'), 'cut_roll_production', ['order_id'], unique=False)
    op.create_index(op.f('ix_cut_roll_production_paper_id'), 'cut_roll_production', ['paper_id'], unique=False)
    op.create_index(op.f('ix_cut_roll_production_plan_id'), 'cut_roll_production', ['plan_id'], unique=False)
    op.create_index(op.f('ix_cut_roll_production_qr_code'), 'cut_roll_production', ['qr_code'], unique=True)
    op.create_index(op.f('ix_cut_roll_production_status'), 'cut_roll_production', ['status'], unique=False)
    op.add_column('pending_order_master', sa.Column('order_item_id', mssql.UNIQUEIDENTIFIER(), nullable=False))
    op.create_index(op.f('ix_pending_order_master_order_item_id'), 'pending_order_master', ['order_item_id'], unique=False)
    op.create_foreign_key(None, 'pending_order_master', 'order_item', ['order_item_id'], ['id'])
    op.add_column('plan_order_link', sa.Column('order_item_id', mssql.UNIQUEIDENTIFIER(), nullable=False))
    op.create_index(op.f('ix_plan_order_link_order_item_id'), 'plan_order_link', ['order_item_id'], unique=False)
    op.create_foreign_key(None, 'plan_order_link', 'order_item', ['order_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plan_order_link', type_='foreignkey')
    op.drop_index(op.f('ix_plan_order_link_order_item_id'), table_name='plan_order_link')
    op.drop_column('plan_order_link', 'order_item_id')
    op.drop_constraint(None, 'pending_order_master', type_='foreignkey')
    op.drop_index(op.f('ix_pending_order_master_order_item_id'), table_name='pending_order_master')
    op.drop_column('pending_order_master', 'order_item_id')
    op.drop_index(op.f('ix_cut_roll_production_status'), table_name='cut_roll_production')
    op.drop_index(op.f('ix_cut_roll_production_qr_code'), table_name='cut_roll_production')
    op.drop_index(op.f('ix_cut_roll_production_plan_id'), table_name='cut_roll_production')
    op.drop_index(op.f('ix_cut_roll_production_paper_id'), table_name='cut_roll_production')
    op.drop_index(op.f('ix_cut_roll_production_order_id'), table_name='cut_roll_production')
    op.drop_index(op.f('ix_cut_roll_production_id'), table_name='cut_roll_production')
    op.drop_index(op.f('ix_cut_roll_production_client_id'), table_name='cut_roll_production')
    op.drop_table('cut_roll_production')
    # ### end Alembic commands ###
