"""Add wastage inventory

Revision ID: c74d6621b178
Revises: ea68956d80d2
Create Date: 2025-08-22 16:21:07.725067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74d6621b178'
down_revision: Union[str, None] = 'ea68956d80d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pending_order_item_included_in_plan_generation', table_name='pending_order_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_pending_order_item_included_in_plan_generation', 'pending_order_item', ['included_in_plan_generation'], unique=False)
    # ### end Alembic commands ###
